<?php
if ( ! defined( 'WPINC' ) ) {
    die;
}

file_put_contents(  MYPLUGIN_HOME_DIR . "/framework/scratch.php" , "" );
include_once( MYPLUGIN_HOME_DIR . '/framework/class-toolbox.php' ); 
include_once( MYPLUGIN_HOME_DIR . '/framework/functions.php' ); 

//Include files in "includes" folder
MYPLUGIN_DFIW_tb::include_folder( "library/" , "php" );
MYPLUGIN_DFIW_tb::include_folder( "php/" , "php" );

class MYPLUGIN_devons_tools_core {

    var $e_css = array(); 

    function __construct(){
        $this->enqueue_files("css");
        $this->enqueue_files("js");
        $this->enqueue_files("php");
    }

    function enqueue_files( $d ){
        $fp = "<?php /*DO NOT EDIT THIS FILE*/";

        file_put_contents(  MYPLUGIN_HOME_DIR . "/framework/scratch.php" , $fp );

        $root_dir = MYPLUGIN_HOME_DIR . '/';

        $directories = scandir( $root_dir . $d );
        //Generate functions file for hooks.
        foreach( $directories as $dir ){
            if ($dir != "admin" && $dir !== '.' && $dir !== '..'){
                if ( is_dir(  $root_dir . $d . '/' . $dir ) ){
                    if ($d != "php"){
                        $fp .= "
                            function MYPLUGIN_" . $dir . " (){
                                MYPLUGIN_DFIW_tb::include_folder( '" . $d . "/" . $dir . "/' , '" . $d . "' );
                            }
                        ";
                    }else{
                        $fp .= "
                            function MYPLUGIN_" . $dir . " (){
                                MYPLUGIN_DFIW_tb::include_folder( '" . $d . "/" . $dir . "/' , 'php' );
                            }
                        ";                        
                    }
                }             
            }
        }
        file_put_contents( MYPLUGIN_HOME_DIR . "/framework/scratch.php" , $fp );  


        foreach( $directories as $dir ){  
            if ($dir != "admin" && $dir !== '.' && $dir !== '..'){
                if ( is_dir(  $root_dir . $d .'/' . $dir ) ){

                    include_once( MYPLUGIN_HOME_DIR . "/framework/scratch.php" );

                    add_action( $dir ,  "MYPLUGIN_" . $dir );

                }
            }
        }
    }
}

new MYPLUGIN_devons_tools_core(); 