<?php
if ( ! defined( 'WPINC' ) ) {
    die;
}

file_put_contents(  MYPLUGIN_HOME_DIR . "/framework/scratch.php" , "" );
include_once( MYPLUGIN_HOME_DIR . '/framework/class-toolbox.php' ); 

//Include files in "includes" folder
MYPLUGIN_DFIW_tb::include_folder( "inc/" , "php" );

class MYPLUGIN_devons_tools_core {

    var $e_css = array(); 

    function __construct(){
        $this->enqueue_files("css");
        $this->enqueue_files("js");
    }

    function enqueue_files( $d ){
        $fp = "<?php /*DO NOT EDIT THIS FILE*/";

        file_put_contents(  MYPLUGIN_HOME_DIR . "/framework/scratch.php" , $fp );

        $directories = scandir( MYPLUGIN_HOME_DIR . '/' . $d );
        //Generate functions file for hooks.
        foreach( $directories as $dir ){
            if ($dir != "admin" && $dir !== '.' && $dir !== '..'){
                if ( is_dir(  MYPLUGIN_HOME_DIR . '/' . $d . '/' . $dir ) ){
                    $fp .= "
                        function MYPLUGIN_" . $dir . " (){
                            MYPLUGIN_DFIW_tb::include_folder( '" . $d . "/" . $dir . "/' , 'css' );
                        }
                    ";
                }             
            }
        }
        file_put_contents( MYPLUGIN_HOME_DIR . "/framework/scratch.php" , $fp );  


        foreach( $directories as $dir ){  
            if ($dir != "admin" && $dir !== '.' && $dir !== '..'){
                if ( is_dir(  MYPLUGIN_HOME_DIR . '/' . $d .'/' . $dir ) ){

                    include_once( MYPLUGIN_HOME_DIR . "/framework/scratch.php" );

                    add_action( $dir ,  "MYPLUGIN_" . $dir );

                }
            }
        }
    }
}

new MYPLUGIN_devons_tools_core(); 

/*
$fp = "<?php /*DO NOT EDIT THIS FILE*//*";

file_put_contents(  MYPLUGIN_HOME_DIR . "/framework/scratch.php" , $fp );

$directories = scandir( MYPLUGIN_HOME_DIR . '/css' );
//Generate functions file for hooks.
foreach( $directories as $dir ){
    if ($dir != "admin" && $dir !== '.' && $dir !== '..'){
        if ( is_dir(  MYPLUGIN_HOME_DIR . '/css/' . $dir ) ){
            $fp .= "
                function MYPLUGIN_" . $dir . " (){
                    MYPLUGIN_DFIW_tb::include_folder( 'css/" . $dir . "/' , 'css' );
                }
            ";
        }             
    }
}
file_put_contents( MYPLUGIN_HOME_DIR . "/framework/scratch.php" , $fp );  


foreach( $directories as $dir ){  
    if ($dir != "admin" && $dir !== '.' && $dir !== '..'){
        if ( is_dir(  MYPLUGIN_HOME_DIR . '/css/' . $dir ) ){

            include_once( MYPLUGIN_HOME_DIR . "/framework/scratch.php" );

            add_action( $dir ,  "MYPLUGIN_" . $dir );

        }
    }
}
*/
