<?php /*DO NOT EDIT THIS FILE*/
                        function MYPLUGIN_wp_enqueue_scripts (){
                            MYPLUGIN_DFIW_tb::include_folder( 'js/wp_enqueue_scripts/' , 'css' );
                        }
                    